FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app

COPY *.gradle ./
COPY gradle ./gradle
COPY gradlew .
RUN chmod +x ./gradlew && ./gradlew dependencies --no-daemon

COPY src ./src

CMD ["./gradlew", "test", "--no-daemon"]


#CMD ["./gradlew", "test", "--tests", "com.softserve.service.*", "--no-daemon"]